steps:
  # Access the id_github file from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud secrets versions access latest --secret=$_GITHUB_SECRET > /root/.ssh/id_github",
      ]
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud secrets versions access latest --secret=$_BITBUCKET_SECRET > /root/.ssh/id_bitbucket",
      ]
    volumes:
      - name: "ssh"
        path: /root/.ssh

  # Set up git with key and domain
  - name: gcr.io/cloud-builders/git
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod 600 /root/.ssh/id_github
        chmod 600 /root/.ssh/id_bitbucket
        cat <<EOF >/root/.ssh/config
        IdentityFile /root/.ssh/id_bitbucket
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
        ssh-keyscan github.com >> /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_IMAGE_REPOSITORY:$SHORT_SHA", "./src"]

  # Build test image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "$_TEST_IMAGE_TAG", "-f", "./src/tests.Dockerfile", "--build-arg", "base_image=$_IMAGE_REPOSITORY:$SHORT_SHA", "./src" ]

  # Run tests
  - name: "$_TEST_IMAGE_TAG"
    dir: "src"

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE_REPOSITORY:$SHORT_SHA"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

timeout: 1800s

substitutions:
  _TEST_IMAGE_TAG: kms-tests
  _IMAGE_REPOSITORY: eu.gcr.io/atlas-275810/mykrobe-atlas-kmersearch-api
  _BITBUCKET_SECRET: ms-bitbucket-readonly
  _GITHUB_SECRET: atlas-jsonschema-readonly
