# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class VariantSearchQuery(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ref=None, pos=None, alt=None, gene=None, genbank=None):  # noqa: E501
        """VariantSearchQuery - a model defined in OpenAPI

        :param ref: The ref of this VariantSearchQuery.  # noqa: E501
        :type ref: str
        :param pos: The pos of this VariantSearchQuery.  # noqa: E501
        :type pos: int
        :param alt: The alt of this VariantSearchQuery.  # noqa: E501
        :type alt: str
        :param gene: The gene of this VariantSearchQuery.  # noqa: E501
        :type gene: str
        :param genbank: The genbank of this VariantSearchQuery.  # noqa: E501
        :type genbank: str
        """
        self.openapi_types = {
            'ref': str,
            'pos': int,
            'alt': str,
            'gene': str,
            'genbank': str
        }

        self.attribute_map = {
            'ref': 'ref',
            'pos': 'pos',
            'alt': 'alt',
            'gene': 'gene',
            'genbank': 'genbank'
        }

        self._ref = ref
        self._pos = pos
        self._alt = alt
        self._gene = gene
        self._genbank = genbank

    @classmethod
    def from_dict(cls, dikt) -> 'VariantSearchQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantSearchQuery of this VariantSearchQuery.  # noqa: E501
        :rtype: VariantSearchQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ref(self):
        """Gets the ref of this VariantSearchQuery.


        :return: The ref of this VariantSearchQuery.
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this VariantSearchQuery.


        :param ref: The ref of this VariantSearchQuery.
        :type ref: str
        """

        self._ref = ref

    @property
    def pos(self):
        """Gets the pos of this VariantSearchQuery.


        :return: The pos of this VariantSearchQuery.
        :rtype: int
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this VariantSearchQuery.


        :param pos: The pos of this VariantSearchQuery.
        :type pos: int
        """

        self._pos = pos

    @property
    def alt(self):
        """Gets the alt of this VariantSearchQuery.


        :return: The alt of this VariantSearchQuery.
        :rtype: str
        """
        return self._alt

    @alt.setter
    def alt(self, alt):
        """Sets the alt of this VariantSearchQuery.


        :param alt: The alt of this VariantSearchQuery.
        :type alt: str
        """

        self._alt = alt

    @property
    def gene(self):
        """Gets the gene of this VariantSearchQuery.


        :return: The gene of this VariantSearchQuery.
        :rtype: str
        """
        return self._gene

    @gene.setter
    def gene(self, gene):
        """Sets the gene of this VariantSearchQuery.


        :param gene: The gene of this VariantSearchQuery.
        :type gene: str
        """

        self._gene = gene

    @property
    def genbank(self):
        """Gets the genbank of this VariantSearchQuery.


        :return: The genbank of this VariantSearchQuery.
        :rtype: str
        """
        return self._genbank

    @genbank.setter
    def genbank(self, genbank):
        """Sets the genbank of this VariantSearchQuery.


        :param genbank: The genbank of this VariantSearchQuery.
        :type genbank: str
        """

        self._genbank = genbank
