openapi: 3.0.1
info:
  title: K-mer Search API
  version: 1.0.0
servers:
  - url: http://kmersearch-api-service/api/v1
paths:
  /search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchQuery'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
        400:
          description: Bad request (i.e. query sequence is too short)
      tags:
        - search
  /variant_search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariantSearchQuery'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariantSearchResults'
      tags:
        - variant_search
  /build:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSamples'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Samples'
      tags:
        - build
components:
  schemas:
    SearchQuery:
      type: object
      properties:
        seq:
          type: string
          minLength: 31
        threshold:
          type: number
    VariantSearchQuery:
      type: object
      properties:
        ref:
          type: string
        pos:
          type: integer
        alt:
          type: string
        gene:
          type: string
        genbank:
          type: string
    SearchResults:
      type: object
      properties:
        query:
          type: string
        threshold:
          type: number
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
    SearchResult:
      type: object
      properties:
        percent_kmers_found:
          type: number
        num_kmers_found:
          type: integer
        num_kmers:
          type: integer
        sample_name:
          type: string
    VariantSearchResults:
      type: object
      properties:
        query:
          type: string
        results:
          type: array
          items:
            $ref: '#/components/schemas/VariantSearchResult'
    VariantSearchResult:
      type: object
      properties:
        genotype:
          type: string
        sample_name:
          type: string
    NewSamples:
      type: object
      properties:
        sample_paths:
          type: array
          items:
            type: string
        sample_names:
          type: array
          items:
            type: string
    Samples:
      type: object
      properties:
        samples:
          type: array
          items:
            $ref: '#/components/schemas/Sample'
    Sample:
      type: object
      properties:
        name:
          type: string
